name: zombies
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-170.0.dev <4.0.0"

dependencies:
  equatable: ^2.0.5
  flame: ^1.13.0
  flame_behaviors: ^1.0.0
  flame_tiled: ^1.13.0
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  assets_gen: ^1.5.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tiles/world.tmx
    - assets/characters/Adventurer/Poses/
    - assets/characters/Zombie/Poses/
    - assets/dungeon/
    - assets/town/
    - assets/Fireball1.png
